//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.driveDetails = new HashSet<driveDetail>();
            this.jobs = new HashSet<job>();
        }
    
        public int companyId { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<driveDetail> driveDetails { get; set; }
        public virtual ICollection<job> jobs { get; set; }
    }
}
