//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OapmsEntities : DbContext
    {
        public OapmsEntities()
            : base("name=OapmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<driveDetail> driveDetails { get; set; }
        public DbSet<hod> hods { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<projectDetail> projectDetails { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<technical> technicals { get; set; }
        public DbSet<tpo> tpoes { get; set; }
    }
}
