//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectDetail
    {
        public int projectId { get; set; }
        public Nullable<int> studentId { get; set; }
        public string projectTitle { get; set; }
        public string description { get; set; }
        public string technology { get; set; }
    
        public virtual student student { get; set; }
    }
}
